name: embedding_layer_variant_analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python
  - python>=3.8
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  
  # R and R packages
  - r-base>=4.0
  - r-reticulate
  - r-stringr
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  
  # Jupyter
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  
  # Development tools
  - pip
  - pip:
    - git+https://github.com/your-repo/embedding_layer_variant_analysis.git
